# Generated by Django 3.1.2 on 2020-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.URLField()),
                ('desc', models.CharField(max_length=500)),
                ('post_type', models.CharField(choices=[('GA', 'Giveaway'), ('OF', 'Offer'), ('EV', 'Event')], default='GA', max_length=3)),
                ('content', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
