# Generated by Django 3.1.2 on 2021-02-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_loc_id',
            field=models.IntegerField(default=0),
        ),
    ]
