# Generated by Django 3.1.2 on 2021-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prevOrdType',
            field=models.CharField(default='Delivery', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_loc_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
