# Generated by Django 3.1.2 on 2021-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210201_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prevOrdType',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
