# Generated by Django 3.1.2 on 2020-11-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('img', models.URLField(default='https://bit.ly/2G85fwJ', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('food_type', models.CharField(choices=[('BRG', 'Burger'), ('FRI', 'Fires'), ('EXT', 'Extra'), ('BVG', 'Beverage')], default='BRG', max_length=3)),
            ],
        ),
    ]
