# Generated by Django 3.1.2 on 2020-11-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_food_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img',
            field=models.CharField(default='https://bit.ly/2G85fwJ', max_length=200),
        ),
    ]
