# Generated by Django 3.1.2 on 2020-11-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_open_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Open_Closed',
        ),
    ]
