# Generated by Django 3.1.2 on 2020-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201125_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
