# Generated by Django 3.1.2 on 2021-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
