# Generated by Django 3.1.2 on 2021-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
