# Generated by Django 3.1.2 on 2020-11-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_order', models.DateTimeField(auto_now_add=True)),
                ('time_of_delivery', models.TimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('customer_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='location.location')),
                ('order', models.ManyToManyField(to='menu.MenuItem')),
            ],
        ),
    ]
