# Generated by Django 3.1.2 on 2020-10-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200)),
                ('time_of_order', models.DateTimeField(auto_now_add=True)),
                ('time_of_delivery', models.TimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('customer', models.CharField(max_length=200)),
                ('customer_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='location.location')),
            ],
        ),
    ]
