# Generated by Django 3.1.2 on 2020-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='+251', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('PCK', 'Pickup'), ('DVY', 'Delivery')], default='DVY', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
    ]
