# Generated by Django 3.1.2 on 2020-11-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
