# Generated by Django 3.1.2 on 2020-11-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0004_remove_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(to='menu.MenuItem'),
        ),
    ]
