# Generated by Django 3.1.2 on 2020-11-17 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20201110_1359'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_auto_20201110_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_location',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_location',
            field=models.ManyToManyField(null=True, to='location.Location'),
        ),
    ]
