# Generated by Django 3.1.2 on 2020-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_delivery',
            field=models.TimeField(null=True),
        ),
    ]
