# Generated by Django 3.1.2 on 2020-11-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20201110_1359'),
        ('order', '0005_auto_20201117_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_location',
            field=models.ManyToManyField(to='location.Location'),
        ),
    ]
