# Generated by Django 3.1.2 on 2020-11-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201117_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_of_delivery',
        ),
    ]
