# Generated by Django 3.1.2 on 2020-11-18 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_time_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
