# Generated by Django 3.1.2 on 2020-11-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_time_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(),
        ),
    ]
