# Generated by Django 3.1.2 on 2021-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201126_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.JSONField(default='extras'),
            preserve_default=False,
        ),
    ]
