# Generated by Django 3.1.2 on 2021-01-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
