# Generated by Django 3.1.2 on 2021-01-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210106_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=models.JSONField(default='extra'),
            preserve_default=False,
        ),
    ]
