# Generated by Django 3.1.2 on 2021-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210106_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
