# Generated by Django 3.1.2 on 2021-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
    ]
